name: Java CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  test:
    name: Build and test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: maven

      - name: Run tests
        # 這裡加上 env，讓測試在 GitHub Actions 跑的時候能讀取到自訂的安全密鑰
        env:
          MY_APP_SECRET: ${{ secrets.APP_SECRET_KEY }} 
        run: mvn --batch-mode test

      - name: Build application
        run: mvn --batch-mode package -DskipTests

  trivy-scan:
    name: Trivy Dependency Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner in fs mode
        uses:aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'          # 指定為檔案系統掃描 (Filesystem)
          scan-ref: '.'            # 掃描當前專案根目錄
          format: 'table'          # 終端機日誌以漂亮的表格呈現
          exit-code: '1'           # 🌟 關鍵設定：如果發現「嚴重 (CRITICAL)」漏洞才讓 CI 亮紅燈中斷
          ignore-unfixed: true     # 忽略目前官方還沒釋出修復修補程式的漏洞（避免無效掉燈）
          vuln-type: 'library'     # 只對專案依賴庫（如 pom.xml 引入的套件）進行掃描
          severity: 'CRITICAL'     # 只攔截最危險的 CRITICAL 等級漏洞

  slscan:
    name: ShiftLeft Security Scan
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Perform slscan
        uses: ShiftLeftSecurity/scan-action@v1.3.0
        with:
          type: "credscan,java,depscan"
        env:
          WORKSPACE: https://github.com/${{ github.repository }}/blob/${{ github.sha }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SCAN_AUTO_BUILD: true

      - name: Upload slscan reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: slscan-reports
          path: reports
