name: Java CI with DevSecOps Scans

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build and test with Maven
        env:
          MY_APP_SECRET: ${{ secrets.APP_SECRET_KEY }}
        run: ./mvnw test

  trivy-scan:
    name: Trivy Dependency Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner in fs mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'library'
          severity: 'CRITICAL'

  security-scan:
    name: ShiftLeft Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Perform slscan
        uses: ShiftLeftSecurity/scan-action@master
        with:
          type: "credscan,java"
          output: "reports"

      - name: Upload scan reports
        uses: actions/artifacts-upload@v2
        if: always()
        with:
          name: slscan-reports
          path: reports